bookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'books/(?P<books_id>\d+)/$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list'),
]

bookstore/bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
    url(r'^cart/',include('carts.urls',namespace='cart')),
    url(r'^order/',include('orders.urls',namespace='order')),

    url(r'^search/', include('haystack.urls')),
]

bookstore/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_check/$',views.login_check,name='login_check'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^user/$',views.user,name='user'),
    url(r'address/$',views.address,name='address'),
    url(r'^order/(?P<page>\d+)?/?$',views.order,name='order'),
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^active/(?P<token>.*)/$', views.register_active, name='active'),
]

bookstore/users/models.py
from django.db import models
from db.base_model import BaseModel
from utils.get_hash import get_hash

# Create your models here.

class PassportManager(models.Manager):
    def check_passport(self, username):
        try:
            passport = self.get(username=username)
        except self.model.DoesNotExist:
            passport = None
        if passport:
            return True
        return False

        
    def add_one_passport(self, username, password, email):
        passport = self.create(username=username, password=get_hash(password), email=email)
        return passport

    def get_one_passport(self, username, password):
        '''根据用户名密码查找账户的信息'''
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:
            # 账户不存在
            passport = None
        return passport

class AddressManager(models.Manager):
    def get_default_address(self,passport_id):
        try:
            addr = self.get(passport_id=passport_id,is_default=True)
        except self.model.DoesNotExist:
            addr = None
        return addr
    def add_one_address(self,passport_id,zip_code,recipient_name,recipient_addr,recipient_phone):
        addr = self.get_default_address(passport_id=passport_id)
        if addr:
            is_default=False
        else:
            is_default=True
        addr = self.create(passport_id=passport_id,
                            recipient_name=recipient_name,
                            recipient_addr=recipient_addr,
                            recipient_phone=recipient_phone,
                            zip_code=zip_code,
                            is_default=is_default)
        return addr   

class Passport(BaseModel):
    username=models.CharField(max_length=20,unique=True,verbose_name='用户名称')
    password=models.CharField(max_length=40,verbose_name='用户密码')
    email=models.EmailField(verbose_name='用户邮箱')
    is_active=models.BooleanField(default=False,verbose_name='激活状态')

    objects=PassportManager()

    class Meta:
        db_table='s_user_account'

class Address(BaseModel):
    recipient_name = models.CharField(max_length=20,verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code = models.CharField(max_length=6,verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认')
    passport = models.ForeignKey('Passport',verbose_name='账户')

    objects = AddressManager()
    
    class Meta:
        db_table = 's_user_address'

bookstore/users/views.py
from django.shortcuts import render,redirect,reverse
from utils.decorators import login_required
import re
from django.core.paginator import Paginator
from orders.models import OrderInfo,OrderGoods
from users.models import Passport,Address
from django.http import JsonResponse,HttpResponse
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from users.tasks import send_active_email
from django.conf import settings
import os
from django.core.mail import send_mail
from django_redis import get_redis_connection
from books.models import Books
# Create your views here.
def register(request):
    return render(request,'users/register.html')


def register_handle(request):
    username=request.POST.get('user_name')
    password=request.POST.get('pwd')
    email=request.POST.get('email')

    if not all([username,password,email]):
        return render(request,'users/register.html',{'errmsg':'参数不能为空!'})
    
    if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
        return render(request,'users/register.html',{'errmsg':'邮箱不合法！'})

    p = Passport.objects.check_passport(username=username)

    if p:
        return render(request, 'users/register.html', {'errmsg': '用户名已存在！'})
    passport = Passport.objects.add_one_passport(username=username, password=password, email=email)

    
    serializer = Serializer(settings.SECRET_KEY, 3600)
    token = serializer.dumps({'confirm':passport.id}) 
    token = token.decode()

    send_mail('书城用户激活', '', settings.EMAIL_FROM, [email], html_message='<a href="http://127.0.0.1:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)

    #send_active_email.delay(token,username,email)
    return redirect(reverse('books:index'))

def login(request):
    if request.COOKIES.get('username'):
        username=request.COOKIES.get('username')
        checked='checked'
    else:
        username=''
        checked=''
    context={
        'username':username,
        'checked':checked,
    }
    return render(request,'users/login.html',context)
        
def login_check(request):
    username=request.POST.get('username')
    password=request.POST.get('password')
    remember=request.POST.get('remember')
    verifycode = request.POST.get('verifycode')

    if not all([username,password,remember, verifycode]):
        return JsonResponse({'res':2})
    if verifycode.upper() != request.session['verifycode']:
        return JsonResponse({'res': 2})


    passport=Passport.objects.get_one_passport(username=username,password=password)
    if passport:
        next_url=reverse('books:index')
        jres=JsonResponse({'res':1,'next_url':next_url})
        if remember=='true':
            jres.set_cookie('username',username,max_age=7*24*3600)
        else:
            jres.delete_cookie('username')
        request.session['islogin']=True
        request.session['username']=username
        request.session['passport_id']=passport.id
        return jres
    else:
        return JsonResponse({'res':0})

def logout(request):
    request.session.flush()
    return redirect(reverse('books:index'))

@login_required
def user(request):
    passport_id=request.session.get('passport_id')
    addr = Address.objects.get_default_address(passport_id=passport_id)
    con = get_redis_connection('default')
    key = 'history_%d' % passport_id
    # 取出用户最近浏览的5个商品的id
    history_li = con.lrange(key, 0, 4)
    # history_li = [21,20,11]
    # print(history_li)
    # 查询数据库,获取用户最近浏览的商品信息
    # books_li = Books.objects.filter(id__in=history_li)
    books_li = []
    for id in history_li:
        books = Books.objects.get_books_by_id(books_id=id)
        books_li.append(books)

    return render(request, 'users/user_center_info.html', {'addr': addr,
                                                           'page': 'user',
                                                           'books_li': books_li})

@login_required
def address(request):
    passport_id = request.session.get('passport_id')
    if request.method == 'GET':
        addr = Address.objects.get_default_address(passport_id=passport_id)
        return render(request,'users/user_center_site.html',{'addr':addr,'page':'address'})
    else:
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        #print(zip_code)
        recipient_phone = request.POST.get('phone')
        if not all([recipient_name,recipient_addr,recipient_phone,zip_code]):
            return render(request,'users/user_center_site.html',{'errmsg':'参数不能为空!'})
        Address.objects.add_one_address(
                                        passport_id=passport_id,
                                        recipient_name=recipient_name,
                                        recipient_addr=recipient_addr,
                                        recipient_phone=recipient_phone,
                                        zip_code=zip_code,
                                            )
        return redirect(reverse('user:address'))
@login_required
def order(request, page):
    passport_id = request.session.get('passport_id')

    order_li = OrderInfo.objects.filter(passport_id=passport_id)

    for order in order_li:
        order_id = order.order_id
        order_books_li = OrderGoods.objects.filter(order_id=order_id)
        #print(order_books_li)
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            amount = count * price
            order_books.amount = amount
            #print(count)
        order.order_books_li = order_books_li
    
    paginator = Paginator(order_li, 3)      # 每页显示3个订单
    
    num_pages = paginator.num_pages
    
    if not page:        # 首次进入时默认进入第一页
        page = 1
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)
        
    order_li = paginator.page(page)
    
    if num_pages < 5:
        pages = range(1, num_pages + 1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages - 4, num_pages + 1)
    else:
        pages = range(page - 2, page + 3)

    context = {
        'order_li': order_li,
        'pages': pages,
    }

    return render(request, 'users/user_center_order.html', context)


def verifycode(request):
    #引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象
    font = ImageFont.truetype(os.path.join(settings.BASE_DIR, "Ubuntu-RI.ttf"), 15)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    #内存文件操作
    import io
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

def register_active(request, token):
    '''用户账户激活'''
    serializer = Serializer(settings.SECRET_KEY, 3600)
    try:
        info = serializer.loads(token)
        passport_id = info['confirm']
        # 进行用户激活
        passport = Passport.objects.get(id=passport_id)
        passport.is_active = True
        passport.save()
        # 跳转的登录页
        return redirect(reverse('user:login'))
    except SignatureExpired:
        # 链接过期
        return HttpResponse('激活链接已过期')

bookstore/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}书城－登录{% endblock %}
{% block topfiles %}
<script>
        $(function () {
            $('#btnLogin').click(function () {
                var username = $("#username").val()
                var password = $("#pwd").val()
                var remember = $('input[name="remember"]').prop('checked')
                var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
                var vc = $('input[name="vc"]').val()
                var params = {
                    'username': username,
                    'password': password,
                    'remember': remember,
                    'csrfmiddlewaretoken': csrfmiddlewaretoken,
                    'verifycode': vc,
                }
                $.post('/user/login_check/', params, function (data) {
                    if (data.res == 1) {
                        location.href = data.next_url;
                    } else if (data.res == 2) {
                        alert("数据不完整");
                    } else if (data.res == 0) {
                        alert("用户名或者密码错误");
                    }
                })
            })
        })


</script>
{% endblock %}
{% block header_con %}{% endblock %}
{% block search_bar %}{% endblock %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'books:index'%}" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学计算机 · 来尚硅谷</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {% csrf_token %}
						<input type="text" id='username' name="username" class="name_input" value='{{ username }}' placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" id='pwd' name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
                        
                        <div style="top: 100px; position: absolute;">
                           <input type="text" id="vc" name="vc" style="height: 25px;width: 180px;">
                           <img id='verifycode' src="/user/verifycode/" onclick="this.src='/user/verifycode/?'+Math.random()" alt="CheckCode"/>
                        </div>
                        
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

                        

						<input type="button" name="" value="登录" class="input_submit" id='btnLogin'>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

bookstore/templates/users/register.html
{% extends 'base.html' %}	
{% load staticfiles %}
{% block title %}书城－注册{% endblock %}
{% block topfiles %}
    {% block cart_count %}{% endblock %}
{% endblock %}
{% block search_bar %}{% endblock %}
{% block header_con %}{% endblock %}

{% block body %}

<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login'%}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method='post' action='/user/register_handle/'>
                {%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”尚硅谷书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
                        {{ errmsg }}
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>



{% endblock %}

bookstore/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}书城－用户中心{% endblock %}
{% block body %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}">· 收货地址</a></li>
            </ul>
        </div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
                        {% if addr %}
							<li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
							<li><span>联系地址：</span>{{ addr.recipient_addr}}</li>			
                        {% else %}
                            <li><span>联系方式：</span>无</li>
                            <li><span>联系地址：</span>无</li> 
                        {% endif %}
						</ul>
				</div>
				

                <h3 class="common_title2">最近浏览</h3>
                <div class="has_view_list">
                    <ul class="book_type_list clearfix">
                        {% for books in books_li %}
                            <li>
                                <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
                                <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
                                <div class="operate">
                                    <span class="price">￥{{ books.price }}</span>
                                    <span class="unit">{{ books.unit }}</span>
                                    <a href="#" class="add_books" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
		</div>
	</div>

{% endblock %}	

bookstore/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}书城－订单页{% endblock %}
{% block topfiles %}{% endblock %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user'%}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
                {% for order in order_li %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">
                    {% if order.status == 1 %}待支付
                    {% elif order.status == 2 %}待发货
                    {% elif order.status == 3 %}待收货
                    {% elif order.status == 4 %}待评价
                    {% else %}已完成{% endif %}
                    </li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for order_books in order.order_books_li %}
                                <ul class="order_book_list clearfix">					
									<li class="col01"><img src="{% static order_books.books.image %}"></li>
									<li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price}}元/{{ order_books.books.unit }}</em></li>	
									<li class="col03">{{ order_books.count }}</li>
									<li class="col04">{{ order_books.amount }}元</li>	
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.total_price }}元</td>
							<td width="15%">{{ order.status | order_status  }}</td>
							<td width="15%"><a href="#"  pay_method='{{ order.pay_method }}' order_id='{{ order.order_id }}' order_status='{{ order.status }}' class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
                </table>
                {% endfor %}
				

				<div class="pagenation">
                {% if order_li.has_previous %} 
					<a href="#">&lt;上一页</a>
                {% endif %}
                {% for page in pages %}
                    {% if page == order_li.number %}
					<a href="{% url 'user:order' page=page %}" class="active">{{ page }}</a>
                    {% else %}
					<a href="{% url 'user:order' page=page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if order_li.has_next %}
					<a href="{% url 'user:order' page=order_li.next_page_number %}">下一页&gt;</a>
                {% endif %}
				</div>
		</div>
	</div>


{% endblock %}

{% block bottomfiles%}
    <script>
    $(function () {
        $('.oper_btn').click(function () {
            // 获取订单id和订单的状态
            var order_id = $(this).attr('order_id')
            var order_status = $(this).attr('order_status')
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {
                        'order_id':order_id,
                        'csrfmiddlewaretoken':csrf
                    }
            console.log(params)
            if (order_status == 1){
                $.post('/order/pay/', params, function (data) {
                    if (data.res == 3){
                        // 把用户引导支付页面
                        window.open(data.pay_url)
                        // 查询用户的支付结果
                        $.post('/order/check_pay/', params, function (data) {
                            if (data.res == 3){
                                alert('支付成功')
                                // 重新刷新页面
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>
{% endblock bottomfiles %}



bookstore/templates/users/user_center_site.html
{% extends 'base.html'%}
{% block title %}收货地址{% endblock %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
            </ul>
        </div> 
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						    <dd>{{ addr.recipient_addr }}({{ addr.recipient_name }}收){{ addr.recipient_phone }}</dd>
                        {% else %}
                            <dd>无</dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method='post' action='/user/address/'>
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name='addr'></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
</div>
{% endblock %}