bookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'books/(?P<books_id>\d+)/$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list'),
]

bookstore/bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
    url(r'^cart/',include('carts.urls',namespace='cart')),
    url(r'^order/',include('orders.urls',namespace='order')),

    url(r'^search/', include('haystack.urls')),
]

bookstore/orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^place/$',views.order_place,name='place'),
    url(r'^commit/$', views.order_commit, name='commit'),
    url(r'^pay/$', views.order_pay, name='pay'), 
    url(r'^check_pay/$', views.check_pay, name='check_pay'),
]

bookstore/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_check/$',views.login_check,name='login_check'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^user/$',views.user,name='user'),
    url(r'address/$',views.address,name='address'),
    url(r'^order/(?P<page>\d+)?/?$',views.order,name='order'),
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^active/(?P<token>.*)/$', views.register_active, name='active'),
]

bookstore/orders/models.py
from django.db import models

# Create your models here.
from django.shortcuts import render
from db.base_model import BaseModel
# Create your views here.

class OrderInfo(BaseModel):
    PAY_METHOD_CHOICES = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝'),
        (4,'银联支付')
    )
    PAY_METHODS_ENUM = {
        'CASH':1,
        'WEIXIN':2,
        'ALIPAY':3,
        'UNIONPAY':4,
    }
    ORDER_STATUS_CHOICES = (
        (1,'待支付'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待评价'),
        (5,'已完成'),
    )
    order_id = models.CharField(max_length=64,primary_key=True,verbose_name='订单编号')
    passport = models.ForeignKey('users.Passport',verbose_name='下单账户')
    addr = models.ForeignKey('users.Address',verbose_name='收货地址')
    total_count = models.IntegerField(default=1,verbose_name='商品总数')
    total_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='订单运费')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES,default=1,verbose_name='支付方式')
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES,default=1,verbose_name='订单状态')
    trade_id = models.CharField(max_length=100,unique=True,null=True,blank=True,verbose_name='支付编号')
    class Meta:
        db_table = 's_order_info'

class OrderGoods(BaseModel):
    order = models.ForeignKey('OrderInfo',verbose_name='所属订单')
    books = models.ForeignKey('books.Books',verbose_name='订单商品')
    count = models.IntegerField(default=1,verbose_name='商品数量')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')
    class Meta:
        db_table = 's_order_books'

bookstore/orders/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from utils.decorators import login_required
from django.http import HttpResponse,JsonResponse
from users.models import Address
from books.models import Books
from django_redis import get_redis_connection
from datetime import datetime
from django.conf import settings
from orders.models import OrderInfo,OrderGoods
import os
import time
from django.db import transaction
from alipay import AliPay
from bookstore import settings

@login_required
def order_place(request):
    books_ids = request.POST.getlist('books_id')
    if not all(books_ids):
        return redirect(reverse('cart:show'))
    passport_id = request.session.get('passport_id')
    addr = Address.objects.get_default_address(passport_id=passport_id)
    books_li = []
    total_count = 0
    total_price = 0
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%passport_id
    
    for books_id in books_ids:
        books = Books.objects.get_books_by_id(books_id=books_id)
        count = conn.hget(cart_key,books_id)
        books.count = count
        amount = int(count)*books.price
        books.amount = amount
        books_li.append(books)
        total_count += int(count)
        total_price += books.amount
    transit_price = 10
    total_pay = total_price + transit_price
    books_ids = ','.join(books_ids)
    context = {
        'addr':addr,
        'books_li':books_li,
        'total_price':total_price,
        'total_count':total_count,
        'transit_price':transit_price,
        'total_pay':total_pay,
        'books_ids':books_ids,
    }
    return render(request,'orders/place_order.html',context)

@transaction.atomic
def order_commit(request):
    if not request.session.has_key('islogin'):
        return JsonResponse({'res':0,'errmsg':'用户未登录'})
    addr_id = request.POST.get('addr_id')
    pay_method = request.POST.get('pay_method')
    books_ids = request.POST.get('books_ids')
    if not all([addr_id,pay_method,books_ids]):
        return JsonResponse({'res':1,'errmsg':'数据不完整'})
    try:
        addr = Address.objects.get(id=int(addr_id))
    except Exception as e:
        return JsonResponse({'res':2,'errmsg':'地址信息错误'})
    if int(pay_method) not in OrderInfo.PAY_METHODS_ENUM.values():
        return JsonResponse({'res':3,'errmsg':'不支持的支付方式'})

    passport_id = request.session.get('passport_id')
    order_id = datetime.now().strftime('%Y%m%d%H%M%S') + str(passport_id)
    transit_price = 10
    total_count = 0
    total_price = 0
    sid = transaction.savepoint()
    try:
        order = OrderInfo.objects.create(
                            order_id=order_id,
                            passport_id=passport_id,
                            addr_id=addr_id,
                            total_count=total_count,
                            transit_price=transit_price,
                            total_price=total_price,
                            pay_method=pay_method)
        books_ids = books_ids.split(',')
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % passport_id
        for id in books_ids:
            books = Books.objects.get_books_by_id(books_id=id)
            if books is None:
                transaction.savepoint_rollback(sid)
                return JsonResponse({'res':4,'errmsg':'商品信息错误'})
            count = conn.hget(cart_key,id)
            if int(count)>books.stock:
                transaction.savepoint_rollback(sid)
                return JsonResponse({'res':5,'errmsg':'商品库存不足'})
            OrderGoods.objects.create(order_id=order_id,
                                    books_id=id,
                                    count=count,
                                    price=books.price)
            books.sales += int(count)
            books.stock -= int(count)
            books.save()
            total_count += int(count)
            total_price += int(count)*books.price

        order.total_count = total_count
        order.total_price = total_price
        order.save()
    except Exception as e:
        transaction.savepoint_rollback(sid)
        return JsonResponse({'res':7,'errmsg':'服务器错误'})

    conn.hdel(cart_key,*books_ids)
    transaction.savepoint_commit(sid)
    return JsonResponse({'res':6})
                        
@login_required
def order_pay(request):
    print(request.POST)
    order_id = request.POST.get('order_id')
    print(order_id)
    if not order_id:
        return JsonResponse({'res':1,'errmsg':'订单不存在'})
    try:
        order = OrderInfo.objects.get(order_id=order_id,
                                        status=1,
                                        pay_method=3)
    except OrderInfo.DoesNotExist:
        return JsonResponse({'res':2,'errmsg':'订单信息出错'})
    app_private_key_path = os.path.join(settings.BASE_DIR,'orders/app_private_key.pem')
    alipay_public_key_path = os.path.join(settings.BASE_DIR,'orders/app_private_key.pem')
    app_private_key_string = open(app_private_key_path).read()
    alipay_public_key_string = open(alipay_public_key_path).read()
    alipay = AliPay(
        appid='2016092000554919',
        app_notify_url=None,
        app_private_key_string=app_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type = 'RSA2',
        debug = True,
    )
    total_pay = order.total_price + order.transit_price
    order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order_id,
        total_amount=str(total_pay),
        subject='书城%s'%order_id,
        return_url=None,
        notify_url=None
    )
    pay_url = settings.ALIPAY_URL + '?' + order_string
    return JsonResponse({'res':3,'pay_url':pay_url,'message':'OK'})


@login_required
def check_pay(request):
    passport_id = request.session.get('passport_id')
    order_id = request.POST.get('order_id')
    if not order_id:
        return JsonResponse({'res':1,'errmsg':'订单不存在'})
    try:
        order = OrderInfo.objects.get(order_id=order_id,
                                    passport_id=passport_id,
                                    pay_method=3)
    except OrderInfo.DoesNotExist:
        return JsonResponse({'res':2,'errmsg':'订单信息出错'})
    app_private_key_path = os.path.join(settings.BASE_DIR,'orders/app_private_key.pem')
    alipay_public_key_path = os.path.join(settings.BASE_DIR,'orders/app_private_key.pem')
    app_private_key_string = open(app_private_key_path).read()
    alipay_public_key_string = open(alipay_public_key_path).read()
    alipay = AliPay(
        appid='2016092000554919',
        app_notify_url=None,
        app_private_key_string=app_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type='RSA2',
        debug = True,
    )

    while True:
        result = alipay.api_alipay_trade_query(order_id)
        code = result.get('code')
        if code == '10000' and result.get('trade_status') == 'TRADE_SUCCESS':
            order.status = 2
            order.trade_id = result.get('trade_no')
            order.save()
            return JsonResponse({'res':3,'message':'支付成功'})
        elif code == '40004' or (code == '10000' and result.get('trade_status') == 'WAIT_BUYER_PAY'):
            time.sleep(5)
            continue
        else:
            return JsonResponse({'res':4,'errmsg':'支付出错'})









   

bookstore/templates/orders/place_order.html
{% extends 'base.html'%}
{% load staticfiles %}
{% block title %}书城－提交订单{% endblock %}
{% block topfiles %}

{% endblock %}
{% block body %}
    {% csrf_token %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="addr_id" value='{{ addr.id}}' checked="">{{ addr.recipient_addr }}</dd>
		</dl>
		<a href="{% url 'user:address'%}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value='1' checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value='2'>
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value='3'>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value='4'>
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="book_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for book in books_li %}
		<ul class="book_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>			
			<li class="col02"><img src="{% static book.image %}"></li>
			<li class="col03">{{ book.name }}</li>
			<li class="col04">{{ book.unit }}</li>
			<li class="col05">{{ book.price }}元</li>
			<li class="col06">{{ book.count }}</li>
			<li class="col07">{{ book.amount }}元</li>	
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_book_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn" books_ids='{{ books_ids }}'>提交订单</a>
	</div>	
{% endblock %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock %}
{% block bottomfiles %}
     <script type="text/javascript">
         $('#order_btn').click(function() {
             var addr_id = $('input[name="addr_id"]').val()
             var pay_method = $('input[name="pay_style"]:checked').val()
             var books_ids = $(this).attr('books_ids')
             var csrf = $('input[name="csrfmiddlewaretoken"]').val()
             var params = {
                 'addr_id': addr_id,
                 'pay_method': pay_method,
                 'books_ids': books_ids,
                 'csrfmiddlewaretoken': csrf
             }
            
             $.post('/order/commit/', params, function (data) {
                 if (data.res == 6){
                     $('.popup_con').fadeIn('fast', function() {
                         setTimeout(function(){
                             $('.popup_con').fadeOut('fast',function(){
                                 window.location.href = '/user/order/';
                             });
                         },3000)
 
                     });
                 }
                 else {
                     alert(data.errmsg)
                 }
             })
 
         });
     </script>
 {% endblock bottomfiles %}
